apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord
  namespace: monitoring
  labels:
    alertmanagerConfig: discord
spec:
  route:
    groupBy: ['alertname']
    groupInterval: 10s
    groupWait: 1s
    repeatInterval: 30s
    receiver: discord
    matchers:
    - name: category
      value: reachability
  receivers:
  - name: discord
    webhookConfigs:
    - url: 'http://192.168.0.231:9094'
