apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
  namespace: monitoring
data:
  address: aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvODQ2Nzg5OTcyODQ5MDY2MDA0L1ZUUlpnNlp6MG1PSWZJRm9NNmFtajR3eUQ4SzAyZHBwbklUUDFGTUZQcjFUeEExdUtiNjJXWDRfLS1wZzRtOEh0TG8t
